language: generic

matrix:

    include: 
        - os: linux
          dist: focal
          arch: arm64-graviton2
          virt: lxd
          group: edge
          language: python
          python: "3.6"

        - os: linux
          dist: focal
          arch: amd64
          language: python
          python: "3.6"


install:
    - sudo apt-get update && sudo apt-get install python3-setuptools
    - pip3 install jaraco.classes
    - pip3 install jaraco.itertools
    - pip3 install func_timeout
    - sudo apt install tox
    - python setup.py install

script:
    - uname -m
    - tox -e py36
